services:
  jenkins:
    container_name: jenkins
    build:
      context: jenkins_conf/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    user: "1000:1000"
    volumes:
      - /home/amin/jenkins_home:/var/jenkins_home
    environment:
      DOCKER_HOST: tcp://dind:2376  
    networks:
      - mynet
    depends_on:
      - dind
  dind:
    image: docker:dind
    container_name: dind
    privileged: true  
    ports:
      - "2375:2375"  
    
    volumes:
      - dind-data:/var/lib/docker  )
    networks:
      - mynet

volumes:
  dind-data:
networks:
  mynet: 