FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
        sudo \
        curl \
        gnupg \
        lsb-release && \
    mkdir -m 0755 -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Trivy
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/aquasecurity/trivy/releases/download/v0.63.0/trivy_0.63.0_Linux-64bit.deb && \
    dpkg -i trivy_0.63.0_Linux-64bit.deb && \
    rm trivy_0.63.0_Linux-64bit.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

