pipeline {
    agent any
    environment {
        registry = "aminbentani2000/node"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    stages {
        stage('Checkout git repo') {
            steps {
                git branch: 'main', url: 'https://github.com/bentaniamin1/express_app.git'
            }
        }
        stage('Building our image') {
            steps{script {dockerImage = docker.build registry + ":$BUILD_NUMBER"}
                
        }
        }
        stage('Pushing image to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}