pipeline {
    agent any
    environment {
        registry = "aminbentani2000/node"
        registryCredential = 'dockerhub_id'
        dockerImage = ''
    }
    stages {
        stage('Checkout git repo') {
            steps {
                git branch: 'main', url: 'https://github.com/bentaniamin1/express_app.git'
            }
        }

        stage('Check filesystem with Trivy') {
            steps {
                script {
                    sh "trivy fs --exit-code 1 --severity CRITICAL --no-progress ."
                }
            }
        }
        
        stage('Building our image') {
            steps{script {dockerImage = docker.build registry + ":$BUILD_NUMBER"}
                
        }
        }
        stage('check image trivy') {
            steps {
                script {
                        sh "trivy --debug image ${registry}:${BUILD_NUMBER}"
                        sh "trivy image --exit-code 1 --severity CRITICAL --no-progress ${registry}:${BUILD_NUMBER}"
                }
            }
        }
        stage('Pushing image to DockerHub test') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}